In [75]:
import fetch_data as fd
import svm
from random import shuffle
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MultiLabelBinarizer
import kernel
import numpy as np
from sklearn import metrics

In [76]:
categories = ['acq','crude','earn']
numberOfTraining = [15,15,15]
numberOfTesting = [1,1,1]

trainData,trainLabels, testData,testLabel = fd.loadData(categories,numberOfTraining,numberOfTesting)

n=2;
l=0.5;

#mlb = MultiLabelBinarizer()
# Takes set of all possible labels, and creates a sparse(?) matrix of 1/0 representations of class	
#s = mlb.fit_transform(trainLabels)

t = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]);

trainKernel = kernel.recursive_kernel(trainData,trainData,2,0.5)

clf = svm.SVC(kernel='precomputed');

clf.fit(trainKernel,t);

#testKernel = kernel.recursive_kernel(trainData,testData,2,0.5)

#pred = clf.predict(testKernel.T)

 47%|██████████████████████████████████████▏                                           | 20/43 [00:35<00:40,  1.77s/it]


  7%|█████▌                                                                             | 3/45 [03:08<44:04, 62.96s/it]


 60%|█████████████████████████████████████████████████▏                                | 24/40 [00:32<00:21,  1.34s/it]


 45%|████████████████████████████████████▋                                             | 17/38 [00:11<00:13,  1.52it/s]


 78%|███████████████████████████████████████████████████████████████▊                  | 28/36 [00:17<00:04,  1.62it/s]


 88%|████████████████████████████████████████████████████████████████████████▎         | 30/34 [00:36<00:04,  1.23s/it]


 23%|██████████████████▋                                                                | 7/31 [00:12<00:44,  1.85s/it]


 34%|████████████████████████████▎                                                     | 10/29 [00:10<00:20,  1.06s/it]


 63%|███████████████████████████████████████████████████▋                              | 17/27 [01:05<00:38,  3.86s/it]


 42%|██████████████████████████████████▏                                               | 10/24 [00:41<00:57,  4.11s/it]


 52%|██████████████████████████████████████████▉                                       | 11/21 [00:26<00:24,  2.43s/it]


 72%|███████████████████████████████████████████████████████████▏                      | 13/18 [00:12<00:04,  1.06it/s]


100%|██████████████████████████████████████████████████████████████████████████████████| 14/14 [00:06<00:00,  2.32it/s]


 60%|██████████████████████████████████████████████████▍                                 | 3/5 [00:00<00:00,  5.82it/s]


100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.39it/s]
0it [00:00, ?it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 45/45 [15:06<00:00, 20.14s/it]


In [ ]:
numberOfTraining = [15,15,15]
numberOfTesting = [8,8,8]
trainData,trainLabels, testData,testLabel = fd.loadData(categories,numberOfTraining,numberOfTesting)
print("hej")
n=2;
l=0.5;

testKernel = kernel.recursive_kernel(trainData,testData,2,0.5)

pred = clf.predict(testKernel.T)

hej
Number of strings are not equal, reverting to slower, non-square, computation of K


 79%|████████████████████████████████████████████████████████████████▉                 | 19/24 [00:09<00:02,  1.99it/s]


 62%|███████████████████████████████████████████████████▎                              | 15/24 [00:03<00:02,  4.22it/s]


 42%|██████████████████████████████████▏                                               | 10/24 [00:04<00:06,  2.27it/s]


 12%|██████████▍                                                                        | 3/24 [00:00<00:06,  3.23it/s]


  8%|██████▉                                                                            | 2/24 [00:00<00:08,  2.57it/s]


 88%|███████████████████████████████████████████████████████████████████████▊          | 21/24 [01:32<00:13,  4.42s/it]


 75%|█████████████████████████████████████████████████████████████▌                    | 18/24 [00:18<00:06,  1.01s/it]


 62%|███████████████████████████████████████████████████▎                              | 15/24 [00:28<00:16,  1.89s/it]


 21%|█████████████████▎                                                                 | 5/24 [00:32<02:03,  6.51s/it]


 96%|██████████████████████████████████████████████████████████████████████████████▌   | 23/24 [00:13<00:00,  1.72it/s]


 54%|████████████████████████████████████████████▍                                     | 13/24 [00:27<00:23,  2.13s/it]


 58%|███████████████████████████████████████████████▊                                  | 14/24 [00:35<00:25,  2.51s/it]


  0%|                                                                                           | 0/24 [00:00<?, ?it/s]


 89%|████████████████████████████████████████████████████████████████████████▉         | 40/45 [16:36<02:04, 24.92s/it]


 12%|██████████▍                                                                        | 3/24 [00:01<00:10,  2.09it/s]

In [74]:
testlabels = [0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2]
prec, rec, fsc, supp = metrics.precision_recall_fscore_support(testlabels, pred)

print(testlabels-pred)
print(prec)
print(rec)
print(fsc)
print(supp)

C:\Users\Loosc\Anaconda3\envs\mladv\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0  0  0  0  0  0  0  0  0  0  1  1  1  0  1
  0  0  1  0  0]
[ 0.   0.4  1. ]
[ 0.   1.   0.5]
[ 0.          0.57142857  0.66666667]
[10 10 10]


In [3]:
categories = ['acq','earn','corn','crude']
numberOfTraining = [114,152,38,76]
numberOfTesting = [25,40,15,10]


categories = ['corn','crude','earn']
numberOfTraining = [15,15,15]
numberOfTesting = [1,1,1]


trainData,trainLabels, testData,testLabel = fd.loadData(categories,numberOfTraining,numberOfTesting)

n = 2 # Length of subsequence
l = 0.5 # Lambda value

 # Generate a classifier that we can use for prediction.
clf = svm.generateClassifier( trainData, trainLabels, n, l)
print('\n Classifier built')


res = svm.predict(testData,trainData,clf,n,l)

print('\n Prediction done')

svm.score(res,testLabel)


 56%|█████████████████████████████████████████████▊                                    | 24/43 [02:21<01:52,  5.90s/it]


  7%|██████                                                                             | 3/41 [00:02<00:27,  1.40it/s]


 70%|█████████████████████████████████████████████████████████▍                        | 28/40 [00:51<00:22,  1.84s/it]


 37%|██████████████████████████████▏                                                   | 14/38 [00:08<00:13,  1.75it/s]


 42%|██████████████████████████████████▏                                               | 15/36 [00:16<00:23,  1.10s/it]


 24%|███████████████████▌                                                               | 8/34 [00:54<02:55,  6.75s/it]


 16%|████████████▉                                                                      | 5/32 [00:08<00:45,  1.70s/it]


 40%|████████████████████████████████▊                                                 | 12/30 [00:04<00:07,  2.43it/s]


 89%|█████████████████████████████████████████████████████████████████████████▏        | 25/28 [02:15<00:16,  5.43s/it]


 24%|███████████████████▉                                                               | 6/25 [00:23<01:14,  3.95s/it]


 91%|██████████████████████████████████████████████████████████████████████████▊       | 21/23 [00:26<00:02,  1.27s/it]


 47%|███████████████████████████████████████▎                                           | 9/19 [00:23<00:25,  2.58s/it]


 64%|████████████████████████████████████████████████████▊                             | 29/45 [23:44<13:05, 49.11s/it]


100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 13.17it/s]


 98%|████████████████████████████████████████████████████████████████████████████████▏ | 44/45 [24:14<00:33, 33.07s/it]
0it [00:00, ?it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 45/45 [24:14<00:00, 32.33s/it]



 Classifier built
Number of strings are not equal, reverting to slower, non-square, computation of K


 42%|██████████████████████████████████▌                                               | 19/45 [00:24<00:33,  1.30s/it]


 89%|████████████████████████████████████████████████████████████████████████▉         | 40/45 [00:43<00:05,  1.09s/it]


100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [02:50<00:00, 56.69s/it]






(3, 45)

 Prediction done
Accuracy: 0.333333333333


In [39]:
print(res)

[[0 0 0]
 [0 0 0]
 [0 0 1]]
